grails-app/controllers/net/openva/server/controllers/ReportsController.groovy
package net.openva.server.controllers

import net.openva.server.Codes
import net.openva.server.model.VerbalAutopsyStats
import net.openva.server.model.logs.LogReport
import net.openva.server.model.logs.LogReportFile
import net.openva.server.model.logs.LogStatus

class ReportsController {

    def verbalAutopsyControlService

    def index() {
        def logReports = LogReport.executeQuery("select lr from LogReport lr where lr.group.groupId in (:list) order by lr.reportId", [list: [Codes.GROUP_STATS]])

        def stats = VerbalAutopsyStats.last()

        stats = stats==null ? new VerbalAutopsyStats() : stats

        render view: "index", model: [logReports : logReports, stats: stats]
    }

    def showLogReport(){
        def logReportInstance = LogReport.get(params.id)

        def logFiles = LogReportFile.executeQuery("select f from LogReportFile f where f.logReport=? order by f.creationDate desc", [logReportInstance])

        render view:"showLogReport", model : [logReportInstance : logReportInstance, logFiles: logFiles]
    }

    def downloadLogFile = {

        def logReportFile = LogReportFile.get(params.id)

        File file = new File(logReportFile.fileName)

        if (file.exists()) {
            response.setContentType("text/plain") // or or image/JPEG or text/xml or whatever type the file is
            response.setHeader("Content-disposition", "attachment;filename=\"${file.name}\"")
            response.outputStream << file.bytes
        } else {
            render "${message(code: "default.file.not.found")} - ${logReportFile.fileName}"
        }

    }

    def executeUpdateStats = {

        LogReport logReport = null

        LogReport.withTransaction {
            logReport = LogReport.get(params.id)
            logReport.status = LogStatus.findByName(LogStatus.STARTED)
            logReport.start = new Date();
            logReport.save(flush: true)
        }

        if (logReport.reportId==Codes.REPORT_VERBAL_AUTOPSY_STATS){
            new Thread(new Runnable() {
                @Override
                void run() {
                    println "executing update of verbal autopsy stats"
                    verbalAutopsyControlService.calculateVaStats(logReport.id)
                }
            }).start()
        }

        redirect (action: "index")
    }
}

grails-app/views/reports/index.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<title><g:message code="default.menu.stats.label" /></title>

		<asset:stylesheet src="main_content.css"/>
	</head>
	<body>

		<div class="nav_menu" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" controller="updates" action="addDeaths"><g:message code="default.menu.add.death.label" /></g:link></li>
				<li><g:link class="create" controller="updates" action="addIndividuals"><g:message code="default.menu.add.individual.label" /></g:link></li>
			</ul>
		</div>
		<div id="list-user" class="content scaffold-list" role="main">
			<h1><g:message code="default.menu.stats.label" /></h1>
			<br>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
						<th><g:message code="logreport.description.label" default="Process Description" /></th>
						<th><g:message code="logreport.start.label" default="Last Synch Start" /></th>
						<th><g:message code="logreport.end.label" default="Last Synch End" /></th>
						<th><g:message code="logreport.status.label" default="Current Status" /></th>
						<th><g:message code="" default="" /></th>
					</tr>
				</thead>
				<tbody>
				<g:each in="${logReports}" status="i" var="logReport">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

						<td><g:link controller="logReport" action="show" id="${logReport.id}"><g:message code="${logReport.description}" default="${logReport.description}" /></g:link></td>

						<td><g:formatDate date="${logReport.start}" format="yyyy-MM-dd HH:mm" /></td>

						<td><g:formatDate date="${logReport.end}" format="yyyy-MM-dd HH:mm" /></td>

						<td><g:message code="${logReport.status}" default="${logReport.status}" /></td>

						<td>
							<g:link class="edit" controller="reports" action="executeUpdateStats" id="${logReport.id}">
								<g:message code="default.execute.label" default="Execute" />
							</g:link>
						</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>

			<div>
				<ol class="property-list stats">
					<li class="fieldcontain">
						<span id="reportId-label" class="property-label"><g:message code="stats.totalDeaths.label" />:</span>
						<span class="property-value" aria-labelledby="reportId-label">${stats.totalDeaths}</span>
					</li>
					<li class="fieldcontain">
						<span id="reportId-label" class="property-label"><g:message code="stats.totalCollected.label" />:</span>
						<span class="property-value" aria-labelledby="reportId-label">${stats.totalCollected}</span>
					</li>
					<li class="fieldcontain">
						<span id="reportId-label" class="property-label"><g:message code="stats.totalToCollect.label" />:</span>
						<span class="property-value" aria-labelledby="reportId-label">${stats.totalToCollect}</span>
					</li>
				</ol>
				<ol class="property-list stats">

					<li class="fieldcontain">
						<span id="reportId-label" class="property-label"><g:message code="stats.totalAttempts.label" />:</span>
						<span class="property-value" aria-labelledby="reportId-label">${stats.totalAttempts}</span>
					</li>
					<li class="fieldcontain">
						<span id="reportId-label" class="property-label"><g:message code="stats.totalAttemptNi.label" />:</span>
						<span class="property-value" aria-labelledby="reportId-label">${stats.totalAttemptNi}</span>
					</li>
					<li class="fieldcontain">
						<span id="reportId-label" class="property-label"><g:message code="stats.totalAttemptUh.label" />:</span>
						<span class="property-value" aria-labelledby="reportId-label">${stats.totalAttemptUh}</span>
					</li>
					<li class="fieldcontain">
						<span id="reportId-label" class="property-label"><g:message code="stats.totalAttemptWdr.label" />:</span>
						<span class="property-value" aria-labelledby="reportId-label">${stats.totalAttemptWdr}</span>
					</li>
					<li class="fieldcontain">
						<span id="reportId-label" class="property-label"><g:message code="stats.totalAttemptOt.label" />:</span>
						<span class="property-value" aria-labelledby="reportId-label">${stats.totalAttemptOt}</span>
					</li>
					<li class="fieldcontain">
						<span id="reportId-label" class="property-label"><g:message code="stats.totalAttemptNc.label" />:</span>
						<span class="property-value" aria-labelledby="reportId-label">${stats.totalAttemptNc}</span>
					</li>

				</ol>
			</div>

			<fieldset class="buttons">
				<g:actionSubmit name="create" class="save" action="exportStats" value="${message(code: "stats.export.label")}" />
			</fieldset>
		</div>
	</body>
</html>

grails-app/views/reports/showLogReport.gsp
<%@ page import="net.openva.server.model.logs.LogReport" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="reportName" value="${message(code: logReportInstance?.description)}" />
		<g:set var="entityName" value="${message(code: 'logReport.label', default: 'LogReport')}" />

		<title><g:message code="default.show.label" args="[entityName]" /></title>

		<asset:stylesheet src="main_content.css"/>
	</head>
	<body>
		<a href="#show-logReport" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav_menu" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
			</ul>
		</div>
		<div id="show-logReport" class="content scaffold-show" role="main">
			<h1><g:message code="logreport.show.label" args="[reportName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list logReport">
			
				<g:if test="${logReportInstance?.reportId}">
				<li class="fieldcontain">
					<span id="reportId-label" class="property-label"><g:message code="logreport.reportId.label" default="Report Id" /></span>
					<span class="property-value" aria-labelledby="reportId-label"><g:fieldValue bean="${logReportInstance}" field="reportId"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${logReportInstance?.group}">
				<li class="fieldcontain">
					<span id="group-label" class="property-label"><g:message code="logreport.group.label" default="Group" /></span>
					<span class="property-value" aria-labelledby="group-label">
						<b>${logReportInstance?.group?.encodeAsHTML()}</b>
					</span>
					
				</li>
				</g:if>
			
				<g:if test="${logReportInstance?.description}">
				<li class="fieldcontain">
					<span id="description-label" class="property-label"><g:message code="logreport.description.label" default="Description" /></span>
					<span class="property-value" aria-labelledby="description-label"><g:message code="${logReportInstance.description}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${logReportInstance?.status}">
				<li class="fieldcontain">
					<span id="status-label" class="property-label"><g:message code="logreport.status.label" default="Status" /></span>
					<span class="property-value" aria-labelledby="status-label">
						<b><g:message code="${logReportInstance?.status}" /></b>
					</span>
					
				</li>
				</g:if>
			
				<g:if test="${logReportInstance?.start}">
				<li class="fieldcontain">
					<span id="start-label" class="property-label"><g:message code="logreport.start.label" default="Start" /></span>
					<span class="property-value" aria-labelledby="start-label"><g:formatDate date="${logReportInstance?.start}" format="yyyy-MM-dd HH:mm:ss" /></span>
				</li>
				</g:if>
			
				<g:if test="${logReportInstance?.end}">
				<li class="fieldcontain">
					<span id="end-label" class="property-label"><g:message code="logreport.end.label" default="End" /></span>
					<span class="property-value" aria-labelledby="end-label"><g:formatDate date="${logReportInstance?.end}" format="yyyy-MM-dd HH:mm:ss" /></span>
				</li>
				</g:if>


				<g:if test="${logReportInstance?.logFiles}">


				<li class="fieldcontain">

					<g:set var="startDate" value="${ (logReportInstance.start!=null) ? logReportInstance.start.time : "" }" />

					<table>
						<thead>
						<tr>
							<g:sortableColumn property="fileName" title="${message(code: 'logReportFile.fileName.label', default: 'File Name')}" />

							<g:sortableColumn property="processedCount" title="${message(code: 'logReportFile.processedCount.label', default: 'Processed Count')}" />

							<g:sortableColumn property="errorsCount" title="${message(code: 'logReportFile.errorsCount.label', default: 'Errors Count')}" />

							<g:sortableColumn property="syncDate" title="${message(code: 'logReportFile.creationDate.label', default: 'Creation Date')}" />

						</tr>
						</thead>
						<tbody>
						<g:each in="${logFiles}" status="i" var="logFileInstance">

							<g:if test="${logFileInstance.creationDate != startDate}">
								<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
									<td><b>Synched on: ${logFileInstance.creationDate}</b></td>
								</tr>
							</g:if>

							<g:set var="startDate" value="${ logFileInstance.creationDate.time }" />

							<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

								<td><g:link action="downloadLogFile" id="${logFileInstance.id}">${fieldValue(bean: logFileInstance, field: "fileName")}</g:link></td>

								<td>${fieldValue(bean: logFileInstance, field: "processedCount")}</td>

								<td>${fieldValue(bean: logFileInstance, field: "errorsCount")}</td>

								<td><g:formatDate date="${logFileInstance.creationDate}" format="yyyy-MM-dd HH:mm" /></td>

							</tr>

						</g:each>
						</tbody>
					</table>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:logReportInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>