grails-app/controllers/net/openva/server/controllers/ExportFilesController.groovy
package net.openva.server.controllers

import grails.rest.RestfulController
import net.openva.io.SystemPath
import net.openva.server.Codes
import net.openva.server.model.logs.LogReport
import net.openva.server.model.logs.LogStatus

class ExportFilesController {

    static responseFormats = ['xml']

    def exportFilesService

    def individuals = {
        def file = new File(SystemPath.getAbsoluteResourcesPath()+File.separator+"individuals.xml")
        render file: file
    }

    def users = {
        def file = new File(SystemPath.getAbsoluteResourcesPath()+File.separator+"users.xml")
        render file: file
    }

    def vacontrols = {
        def file = new File(SystemPath.getAbsoluteResourcesPath()+File.separator+"vacontrols.xml")
        render file: file
    }

    def stats = {
        def file = new File(SystemPath.getAbsoluteResourcesPath()+File.separator+"vastats.xml")
        render file: file
    }

    def individualsZip = {
        def file = new File(SystemPath.getAbsoluteResourcesPath()+File.separator+"individuals.zip")
        render file: file, fileName: "individuals.zip"
    }

    def usersZip = {
        def file = new File(SystemPath.getAbsoluteResourcesPath()+File.separator+"users.zip")
        render file: file, fileName: "users.zip"
    }

    def vacontrolsZip = {
        def file = new File(SystemPath.getAbsoluteResourcesPath()+File.separator+"vacontrols.zip")
        render file: file, fileName: "vacontrols.zip"
    }

    def statsZip = {
        def file = new File(SystemPath.getAbsoluteResourcesPath()+File.separator+"vastats.zip")
        render file: file, fileName: "vastats.zip"
    }

    def index = {

        def logReports = LogReport.executeQuery("select lr from LogReport lr where lr.group.groupId=?", [Codes.GROUP_GENERATE_FILES])

        render view: "index", model: [logReports : logReports]
    }

    def export = {
        LogReport logReport = null

        LogReport.withTransaction {
            logReport = LogReport.get(params.id)
            logReport.status = LogStatus.findByName(LogStatus.STARTED)
            logReport.start = new Date();
            logReport.save(flush: true)
        }


        println "log ${logReport.errors}"

        def id = logReport.id

        if (logReport.reportId==Codes.REPORT_GENERATE_USERS_ZIP_XML_FILES){
            new Thread(new Runnable() {
                @Override
                void run() {
                    println "executing export files to user xml/zip"
                    exportFilesService.generateUsersXML(id)
                }
            }).start()
        }

        if (logReport.reportId==Codes.REPORT_GENERATE_INDIVIDUALS_ZIP_XML_FILES){
            new Thread(new Runnable() {
                @Override
                void run() {
                    println "executing export files to individuals xml/zip"
                    exportFilesService.generateLiveIndividualXML(id)
                }
            }).start()
        }

        if (logReport.reportId==Codes.REPORT_GENERATE_VACONTROL_ZIP_XML_FILES){
            new Thread(new Runnable() {
                @Override
                void run() {
                    println "executing export files to vacontrol xml/zip"
                    exportFilesService.generateVaControlXML(id)
                }
            }).start()
        }

        if (logReport.reportId==Codes.REPORT_GENERATE_STATS_ZIP_XML_FILES){
            new Thread(new Runnable() {
                @Override
                void run() {
                    println "executing export files to stats xml/zip"
                    exportFilesService.generateVaStatsXML(id)
                }
            }).start()
        }

        redirect action:'index'
    }
}

grails-app/views/exportFiles/index.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<title><g:message code="default.menu.sync.execute.title" /></title>

		<asset:stylesheet src="main_content.css"/>
	</head>
	<body>

		<div class="nav_menu" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="import" controller="importData" action="index"><g:message code="default.menu.add.import.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-user" class="content scaffold-list" role="main">
			<h1><g:message code="default.menu.sync.execute.title" /></h1>
			<br>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>

						<th><g:message code="" default="Id" /></th>
						<th><g:message code="logreport.description.label" default="Process Description" /></th>
						<th><g:message code="logreport.start.label" default="Last Synch Start" /></th>
						<th><g:message code="logreport.end.label" default="Last Synch End" /></th>
						<th><g:message code="logreport.status.label" default="Current Status" /></th>
						<th><g:message code="" default="" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${logReports}" status="i" var="logReport">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

						<td><g:link controller="logReport" action="show" id="${logReport.id}">${fieldValue(bean: logReport, field: "reportId")}</g:link></td>

						<td><g:message code="${logReport.description}" default="${logReport.description}" /></td>

						<td><g:formatDate date="${logReport.start}" format="yyyy-MM-dd HH:mm" /></td>

						<td><g:formatDate date="${logReport.end}" format="yyyy-MM-dd HH:mm" /></td>

						<td><g:message code="${logReport.status}" default="${logReport.status}" /></td>

						<td>
							<g:link class="edit" controller="exportFiles" action="export" id="${logReport.id}">
								<g:message code="default.execute.label" default="Execute" />
							</g:link>
						</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>

			<fieldset class="buttons">

			</fieldset>
		</div>
	</body>
</html>